# Generated by Django 3.1.3 on 2020-11-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201124_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shortName',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='shortName',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='shortName',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
