# Generated by Django 3.1.3 on 2020-11-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tags',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
