# Generated by Django 3.1.3 on 2020-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201124_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortAbout',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(default='', max_length=10240),
        ),
    ]
