# Generated by Django 3.1.3 on 2020-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201201_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(default='', max_length=10240),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortAbout',
            field=models.TextField(default='', max_length=512),
        ),
    ]
