# Generated by Django 3.1.3 on 2020-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201201_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
