# Generated by Django 3.1.3 on 2020-12-08 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 21, 4, 51, 912377, tzinfo=utc)),
        ),
    ]
