# Generated by Django 3.1.3 on 2020-12-08 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201208_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 22, 18, 59, 235684, tzinfo=utc)),
        ),
    ]
